In [2]:
import torch
x = torch.rand(5,3)
print(x)
torch.cuda.is_available()

tensor([[0.8964, 0.6647, 0.1994],
        [0.1774, 0.0186, 0.8362],
        [0.3474, 0.8728, 0.1598],
        [0.5758, 0.9250, 0.9303],
        [0.3708, 0.9258, 0.2039]])


True

In [3]:
#랭크2 텐서
x = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
print(x)
print("Size:",x.size())
print("Shape:",x.shape)
print("랭크(차원):",x.ndimension())

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Size: torch.Size([3, 3])
Shape: torch.Size([3, 3])
랭크(차원): 2


In [4]:
x=torch.unsqueeze(x,0)
print(x)
print("Size:",x.size())
print("Shape:",x.shape)
print("랭크(차원):",x.ndimension())

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
Size: torch.Size([1, 3, 3])
Shape: torch.Size([1, 3, 3])
랭크(차원): 3


In [5]:
x=torch.squeeze(x)
print(x)
print("Size:",x.size())
print("Shape:",x.shape)
print("랭크(차원):",x.ndimension())

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Size: torch.Size([3, 3])
Shape: torch.Size([3, 3])
랭크(차원): 2


In [6]:
x=x.view(9,1)
print(x)
print("Size:",x.size())
print("Shape:",x.shape)
print("랭크(차원):",x.ndimension())

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])
Size: torch.Size([9, 1])
Shape: torch.Size([9, 1])
랭크(차원): 2


In [7]:
x=x.view(1,9)
print(x)
print("Size:",x.size())
print("Shape:",x.shape)
print("랭크(차원):",x.ndimension())

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])
Size: torch.Size([1, 9])
Shape: torch.Size([1, 9])
랭크(차원): 2


In [8]:
x=x.view(9)
print(x)
print("Size:",x.size())
print("Shape:",x.shape)
print("랭크(차원):",x.ndimension())

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
Size: torch.Size([9])
Shape: torch.Size([9])
랭크(차원): 1


In [9]:
#행렬 곱
w=torch.tensor([[1,2,3],[4,5,6]])
x=torch.tensor([[1,2],[3,4],[5,6]])
wx=torch.mm(w,x)
print(wx)
print(wx.size())

tensor([[22, 28],
        [49, 64]])
torch.Size([2, 2])


In [10]:
#합
b=torch.randn(2,2, dtype=torch.float)
print(b)
result=wx+b
print(result)
print(result.size())

tensor([[-0.7799, -0.5208],
        [ 0.6781, -0.9638]])
tensor([[21.2201, 27.4792],
        [49.6781, 63.0362]])
torch.Size([2, 2])


In [16]:
w=torch.tensor(1.0, requires_grad=True)
a=w*3
l=a**2
l.backward()
print(w.grad)

tensor(18.)
